name: 'ssh-agent-deploy-key'
description: 'GitHub Action to setup ssh-agent and GitHub Deploy keys with private keys'
inputs:
  ssh-private-key:
    description: Private SSH key(s) to register in the SSH agent
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
  post: 'dist/index.js'
  post-if: 'always()'
branding:
  icon: chevrons-down
  color: blue
