name: 'ssh-agent-deploy-key'
description: 'GitHub Action to setup ssh-agent and GitHub Deploy keys with private keys'
inputs:
  ssh-private-key:
    description: Private SSH key(s) to register in the SSH agent
    required: true
  ssh-known-hosts:
    description: >
      Known hosts in addition to the user and global host key database. The
      public SSH keys for a host may be obtained using the utility
      `ssh-keyscan`. For example, `ssh-keyscan github.com`.
runs:
  using: 'node16'
  main: 'dist/index.js'
  post: 'dist/index.js'
  post-if: 'always()'
branding:
  icon: chevrons-down
  color: blue
